package input

// This is a very ugly hack to allow for "repeated" fields in the YAML file.
type ModuleParams struct {
	Order            []string               `yaml:"order"`
	Topoaa           map[string]interface{} `yaml:"topoaa"`
	Topoaa_0         map[string]interface{} `yaml:"topoaa.0"`
	Topoaa_1         map[string]interface{} `yaml:"topoaa.1"`
	Topoaa_2         map[string]interface{} `yaml:"topoaa.2"`
	Topoaa_3         map[string]interface{} `yaml:"topoaa.3"`
	Topoaa_4         map[string]interface{} `yaml:"topoaa.4"`
	Topoaa_5         map[string]interface{} `yaml:"topoaa.5"`
	Topoaa_6         map[string]interface{} `yaml:"topoaa.6"`
	Topoaa_7         map[string]interface{} `yaml:"topoaa.7"`
	Topoaa_8         map[string]interface{} `yaml:"topoaa.8"`
	Topoaa_9         map[string]interface{} `yaml:"topoaa.9"`
	Topoaa_10        map[string]interface{} `yaml:"topoaa.10"`
	Topoaa_11        map[string]interface{} `yaml:"topoaa.11"`
	Topoaa_12        map[string]interface{} `yaml:"topoaa.12"`
	Topoaa_13        map[string]interface{} `yaml:"topoaa.13"`
	Topoaa_14        map[string]interface{} `yaml:"topoaa.14"`
	Topoaa_15        map[string]interface{} `yaml:"topoaa.15"`
	Topoaa_16        map[string]interface{} `yaml:"topoaa.16"`
	Topoaa_17        map[string]interface{} `yaml:"topoaa.17"`
	Topoaa_18        map[string]interface{} `yaml:"topoaa.18"`
	Topoaa_19        map[string]interface{} `yaml:"topoaa.19"`
	Topoaa_20        map[string]interface{} `yaml:"topoaa.20"`
	Topoaa_21        map[string]interface{} `yaml:"topoaa.21"`
	Topoaa_22        map[string]interface{} `yaml:"topoaa.22"`
	Topoaa_23        map[string]interface{} `yaml:"topoaa.23"`
	Topoaa_24        map[string]interface{} `yaml:"topoaa.24"`
	Topoaa_25        map[string]interface{} `yaml:"topoaa.25"`
	Topocg           map[string]interface{} `yaml:"topocg"`
	Topocg_0         map[string]interface{} `yaml:"topocg.0"`
	Topocg_1         map[string]interface{} `yaml:"topocg.1"`
	Topocg_2         map[string]interface{} `yaml:"topocg.2"`
	Topocg_3         map[string]interface{} `yaml:"topocg.3"`
	Topocg_4         map[string]interface{} `yaml:"topocg.4"`
	Topocg_5         map[string]interface{} `yaml:"topocg.5"`
	Topocg_6         map[string]interface{} `yaml:"topocg.6"`
	Topocg_7         map[string]interface{} `yaml:"topocg.7"`
	Topocg_8         map[string]interface{} `yaml:"topocg.8"`
	Topocg_9         map[string]interface{} `yaml:"topocg.9"`
	Topocg_10        map[string]interface{} `yaml:"topocg.10"`
	Topocg_11        map[string]interface{} `yaml:"topocg.11"`
	Topocg_12        map[string]interface{} `yaml:"topocg.12"`
	Topocg_13        map[string]interface{} `yaml:"topocg.13"`
	Topocg_14        map[string]interface{} `yaml:"topocg.14"`
	Topocg_15        map[string]interface{} `yaml:"topocg.15"`
	Topocg_16        map[string]interface{} `yaml:"topocg.16"`
	Topocg_17        map[string]interface{} `yaml:"topocg.17"`
	Topocg_18        map[string]interface{} `yaml:"topocg.18"`
	Topocg_19        map[string]interface{} `yaml:"topocg.19"`
	Topocg_20        map[string]interface{} `yaml:"topocg.20"`
	Topocg_21        map[string]interface{} `yaml:"topocg.21"`
	Topocg_22        map[string]interface{} `yaml:"topocg.22"`
	Topocg_23        map[string]interface{} `yaml:"topocg.23"`
	Topocg_24        map[string]interface{} `yaml:"topocg.24"`
	Topocg_25        map[string]interface{} `yaml:"topocg.25"`
	Exit             map[string]interface{} `yaml:"exit"`
	Exit_0           map[string]interface{} `yaml:"exit.0"`
	Exit_1           map[string]interface{} `yaml:"exit.1"`
	Exit_2           map[string]interface{} `yaml:"exit.2"`
	Exit_3           map[string]interface{} `yaml:"exit.3"`
	Exit_4           map[string]interface{} `yaml:"exit.4"`
	Exit_5           map[string]interface{} `yaml:"exit.5"`
	Exit_6           map[string]interface{} `yaml:"exit.6"`
	Exit_7           map[string]interface{} `yaml:"exit.7"`
	Exit_8           map[string]interface{} `yaml:"exit.8"`
	Exit_9           map[string]interface{} `yaml:"exit.9"`
	Exit_10          map[string]interface{} `yaml:"exit.10"`
	Exit_11          map[string]interface{} `yaml:"exit.11"`
	Exit_12          map[string]interface{} `yaml:"exit.12"`
	Exit_13          map[string]interface{} `yaml:"exit.13"`
	Exit_14          map[string]interface{} `yaml:"exit.14"`
	Exit_15          map[string]interface{} `yaml:"exit.15"`
	Exit_16          map[string]interface{} `yaml:"exit.16"`
	Exit_17          map[string]interface{} `yaml:"exit.17"`
	Exit_18          map[string]interface{} `yaml:"exit.18"`
	Exit_19          map[string]interface{} `yaml:"exit.19"`
	Exit_20          map[string]interface{} `yaml:"exit.20"`
	Exit_21          map[string]interface{} `yaml:"exit.21"`
	Exit_22          map[string]interface{} `yaml:"exit.22"`
	Exit_23          map[string]interface{} `yaml:"exit.23"`
	Exit_24          map[string]interface{} `yaml:"exit.24"`
	Exit_25          map[string]interface{} `yaml:"exit.25"`
	Emref            map[string]interface{} `yaml:"emref"`
	Emref_0          map[string]interface{} `yaml:"emref.0"`
	Emref_1          map[string]interface{} `yaml:"emref.1"`
	Emref_2          map[string]interface{} `yaml:"emref.2"`
	Emref_3          map[string]interface{} `yaml:"emref.3"`
	Emref_4          map[string]interface{} `yaml:"emref.4"`
	Emref_5          map[string]interface{} `yaml:"emref.5"`
	Emref_6          map[string]interface{} `yaml:"emref.6"`
	Emref_7          map[string]interface{} `yaml:"emref.7"`
	Emref_8          map[string]interface{} `yaml:"emref.8"`
	Emref_9          map[string]interface{} `yaml:"emref.9"`
	Emref_10         map[string]interface{} `yaml:"emref.10"`
	Emref_11         map[string]interface{} `yaml:"emref.11"`
	Emref_12         map[string]interface{} `yaml:"emref.12"`
	Emref_13         map[string]interface{} `yaml:"emref.13"`
	Emref_14         map[string]interface{} `yaml:"emref.14"`
	Emref_15         map[string]interface{} `yaml:"emref.15"`
	Emref_16         map[string]interface{} `yaml:"emref.16"`
	Emref_17         map[string]interface{} `yaml:"emref.17"`
	Emref_18         map[string]interface{} `yaml:"emref.18"`
	Emref_19         map[string]interface{} `yaml:"emref.19"`
	Emref_20         map[string]interface{} `yaml:"emref.20"`
	Emref_21         map[string]interface{} `yaml:"emref.21"`
	Emref_22         map[string]interface{} `yaml:"emref.22"`
	Emref_23         map[string]interface{} `yaml:"emref.23"`
	Emref_24         map[string]interface{} `yaml:"emref.24"`
	Emref_25         map[string]interface{} `yaml:"emref.25"`
	Flexref          map[string]interface{} `yaml:"flexref"`
	Flexref_0        map[string]interface{} `yaml:"flexref.0"`
	Flexref_1        map[string]interface{} `yaml:"flexref.1"`
	Flexref_2        map[string]interface{} `yaml:"flexref.2"`
	Flexref_3        map[string]interface{} `yaml:"flexref.3"`
	Flexref_4        map[string]interface{} `yaml:"flexref.4"`
	Flexref_5        map[string]interface{} `yaml:"flexref.5"`
	Flexref_6        map[string]interface{} `yaml:"flexref.6"`
	Flexref_7        map[string]interface{} `yaml:"flexref.7"`
	Flexref_8        map[string]interface{} `yaml:"flexref.8"`
	Flexref_9        map[string]interface{} `yaml:"flexref.9"`
	Flexref_10       map[string]interface{} `yaml:"flexref.10"`
	Flexref_11       map[string]interface{} `yaml:"flexref.11"`
	Flexref_12       map[string]interface{} `yaml:"flexref.12"`
	Flexref_13       map[string]interface{} `yaml:"flexref.13"`
	Flexref_14       map[string]interface{} `yaml:"flexref.14"`
	Flexref_15       map[string]interface{} `yaml:"flexref.15"`
	Flexref_16       map[string]interface{} `yaml:"flexref.16"`
	Flexref_17       map[string]interface{} `yaml:"flexref.17"`
	Flexref_18       map[string]interface{} `yaml:"flexref.18"`
	Flexref_19       map[string]interface{} `yaml:"flexref.19"`
	Flexref_20       map[string]interface{} `yaml:"flexref.20"`
	Flexref_21       map[string]interface{} `yaml:"flexref.21"`
	Flexref_22       map[string]interface{} `yaml:"flexref.22"`
	Flexref_23       map[string]interface{} `yaml:"flexref.23"`
	Flexref_24       map[string]interface{} `yaml:"flexref.24"`
	Flexref_25       map[string]interface{} `yaml:"flexref.25"`
	Mdref            map[string]interface{} `yaml:"mdref"`
	Mdref_0          map[string]interface{} `yaml:"mdref.0"`
	Mdref_1          map[string]interface{} `yaml:"mdref.1"`
	Mdref_2          map[string]interface{} `yaml:"mdref.2"`
	Mdref_3          map[string]interface{} `yaml:"mdref.3"`
	Mdref_4          map[string]interface{} `yaml:"mdref.4"`
	Mdref_5          map[string]interface{} `yaml:"mdref.5"`
	Mdref_6          map[string]interface{} `yaml:"mdref.6"`
	Mdref_7          map[string]interface{} `yaml:"mdref.7"`
	Mdref_8          map[string]interface{} `yaml:"mdref.8"`
	Mdref_9          map[string]interface{} `yaml:"mdref.9"`
	Mdref_10         map[string]interface{} `yaml:"mdref.10"`
	Mdref_11         map[string]interface{} `yaml:"mdref.11"`
	Mdref_12         map[string]interface{} `yaml:"mdref.12"`
	Mdref_13         map[string]interface{} `yaml:"mdref.13"`
	Mdref_14         map[string]interface{} `yaml:"mdref.14"`
	Mdref_15         map[string]interface{} `yaml:"mdref.15"`
	Mdref_16         map[string]interface{} `yaml:"mdref.16"`
	Mdref_17         map[string]interface{} `yaml:"mdref.17"`
	Mdref_18         map[string]interface{} `yaml:"mdref.18"`
	Mdref_19         map[string]interface{} `yaml:"mdref.19"`
	Mdref_20         map[string]interface{} `yaml:"mdref.20"`
	Mdref_21         map[string]interface{} `yaml:"mdref.21"`
	Mdref_22         map[string]interface{} `yaml:"mdref.22"`
	Mdref_23         map[string]interface{} `yaml:"mdref.23"`
	Mdref_24         map[string]interface{} `yaml:"mdref.24"`
	Mdref_25         map[string]interface{} `yaml:"mdref.25"`
	Gdock            map[string]interface{} `yaml:"gdock"`
	Gdock_0          map[string]interface{} `yaml:"gdock.0"`
	Gdock_1          map[string]interface{} `yaml:"gdock.1"`
	Gdock_2          map[string]interface{} `yaml:"gdock.2"`
	Gdock_3          map[string]interface{} `yaml:"gdock.3"`
	Gdock_4          map[string]interface{} `yaml:"gdock.4"`
	Gdock_5          map[string]interface{} `yaml:"gdock.5"`
	Gdock_6          map[string]interface{} `yaml:"gdock.6"`
	Gdock_7          map[string]interface{} `yaml:"gdock.7"`
	Gdock_8          map[string]interface{} `yaml:"gdock.8"`
	Gdock_9          map[string]interface{} `yaml:"gdock.9"`
	Gdock_10         map[string]interface{} `yaml:"gdock.10"`
	Gdock_11         map[string]interface{} `yaml:"gdock.11"`
	Gdock_12         map[string]interface{} `yaml:"gdock.12"`
	Gdock_13         map[string]interface{} `yaml:"gdock.13"`
	Gdock_14         map[string]interface{} `yaml:"gdock.14"`
	Gdock_15         map[string]interface{} `yaml:"gdock.15"`
	Gdock_16         map[string]interface{} `yaml:"gdock.16"`
	Gdock_17         map[string]interface{} `yaml:"gdock.17"`
	Gdock_18         map[string]interface{} `yaml:"gdock.18"`
	Gdock_19         map[string]interface{} `yaml:"gdock.19"`
	Gdock_20         map[string]interface{} `yaml:"gdock.20"`
	Gdock_21         map[string]interface{} `yaml:"gdock.21"`
	Gdock_22         map[string]interface{} `yaml:"gdock.22"`
	Gdock_23         map[string]interface{} `yaml:"gdock.23"`
	Gdock_24         map[string]interface{} `yaml:"gdock.24"`
	Gdock_25         map[string]interface{} `yaml:"gdock.25"`
	Lightdock        map[string]interface{} `yaml:"lightdock"`
	Lightdock_0      map[string]interface{} `yaml:"lightdock.0"`
	Lightdock_1      map[string]interface{} `yaml:"lightdock.1"`
	Lightdock_2      map[string]interface{} `yaml:"lightdock.2"`
	Lightdock_3      map[string]interface{} `yaml:"lightdock.3"`
	Lightdock_4      map[string]interface{} `yaml:"lightdock.4"`
	Lightdock_5      map[string]interface{} `yaml:"lightdock.5"`
	Lightdock_6      map[string]interface{} `yaml:"lightdock.6"`
	Lightdock_7      map[string]interface{} `yaml:"lightdock.7"`
	Lightdock_8      map[string]interface{} `yaml:"lightdock.8"`
	Lightdock_9      map[string]interface{} `yaml:"lightdock.9"`
	Lightdock_10     map[string]interface{} `yaml:"lightdock.10"`
	Lightdock_11     map[string]interface{} `yaml:"lightdock.11"`
	Lightdock_12     map[string]interface{} `yaml:"lightdock.12"`
	Lightdock_13     map[string]interface{} `yaml:"lightdock.13"`
	Lightdock_14     map[string]interface{} `yaml:"lightdock.14"`
	Lightdock_15     map[string]interface{} `yaml:"lightdock.15"`
	Lightdock_16     map[string]interface{} `yaml:"lightdock.16"`
	Lightdock_17     map[string]interface{} `yaml:"lightdock.17"`
	Lightdock_18     map[string]interface{} `yaml:"lightdock.18"`
	Lightdock_19     map[string]interface{} `yaml:"lightdock.19"`
	Lightdock_20     map[string]interface{} `yaml:"lightdock.20"`
	Lightdock_21     map[string]interface{} `yaml:"lightdock.21"`
	Lightdock_22     map[string]interface{} `yaml:"lightdock.22"`
	Lightdock_23     map[string]interface{} `yaml:"lightdock.23"`
	Lightdock_24     map[string]interface{} `yaml:"lightdock.24"`
	Lightdock_25     map[string]interface{} `yaml:"lightdock.25"`
	Rigidbody        map[string]interface{} `yaml:"rigidbody"`
	Rigidbody_0      map[string]interface{} `yaml:"rigidbody.0"`
	Rigidbody_1      map[string]interface{} `yaml:"rigidbody.1"`
	Rigidbody_2      map[string]interface{} `yaml:"rigidbody.2"`
	Rigidbody_3      map[string]interface{} `yaml:"rigidbody.3"`
	Rigidbody_4      map[string]interface{} `yaml:"rigidbody.4"`
	Rigidbody_5      map[string]interface{} `yaml:"rigidbody.5"`
	Rigidbody_6      map[string]interface{} `yaml:"rigidbody.6"`
	Rigidbody_7      map[string]interface{} `yaml:"rigidbody.7"`
	Rigidbody_8      map[string]interface{} `yaml:"rigidbody.8"`
	Rigidbody_9      map[string]interface{} `yaml:"rigidbody.9"`
	Rigidbody_10     map[string]interface{} `yaml:"rigidbody.10"`
	Rigidbody_11     map[string]interface{} `yaml:"rigidbody.11"`
	Rigidbody_12     map[string]interface{} `yaml:"rigidbody.12"`
	Rigidbody_13     map[string]interface{} `yaml:"rigidbody.13"`
	Rigidbody_14     map[string]interface{} `yaml:"rigidbody.14"`
	Rigidbody_15     map[string]interface{} `yaml:"rigidbody.15"`
	Rigidbody_16     map[string]interface{} `yaml:"rigidbody.16"`
	Rigidbody_17     map[string]interface{} `yaml:"rigidbody.17"`
	Rigidbody_18     map[string]interface{} `yaml:"rigidbody.18"`
	Rigidbody_19     map[string]interface{} `yaml:"rigidbody.19"`
	Rigidbody_20     map[string]interface{} `yaml:"rigidbody.20"`
	Rigidbody_21     map[string]interface{} `yaml:"rigidbody.21"`
	Rigidbody_22     map[string]interface{} `yaml:"rigidbody.22"`
	Rigidbody_23     map[string]interface{} `yaml:"rigidbody.23"`
	Rigidbody_24     map[string]interface{} `yaml:"rigidbody.24"`
	Rigidbody_25     map[string]interface{} `yaml:"rigidbody.25"`
	Emscoring        map[string]interface{} `yaml:"emscoring"`
	Emscoring_0      map[string]interface{} `yaml:"emscoring.0"`
	Emscoring_1      map[string]interface{} `yaml:"emscoring.1"`
	Emscoring_2      map[string]interface{} `yaml:"emscoring.2"`
	Emscoring_3      map[string]interface{} `yaml:"emscoring.3"`
	Emscoring_4      map[string]interface{} `yaml:"emscoring.4"`
	Emscoring_5      map[string]interface{} `yaml:"emscoring.5"`
	Emscoring_6      map[string]interface{} `yaml:"emscoring.6"`
	Emscoring_7      map[string]interface{} `yaml:"emscoring.7"`
	Emscoring_8      map[string]interface{} `yaml:"emscoring.8"`
	Emscoring_9      map[string]interface{} `yaml:"emscoring.9"`
	Emscoring_10     map[string]interface{} `yaml:"emscoring.10"`
	Emscoring_11     map[string]interface{} `yaml:"emscoring.11"`
	Emscoring_12     map[string]interface{} `yaml:"emscoring.12"`
	Emscoring_13     map[string]interface{} `yaml:"emscoring.13"`
	Emscoring_14     map[string]interface{} `yaml:"emscoring.14"`
	Emscoring_15     map[string]interface{} `yaml:"emscoring.15"`
	Emscoring_16     map[string]interface{} `yaml:"emscoring.16"`
	Emscoring_17     map[string]interface{} `yaml:"emscoring.17"`
	Emscoring_18     map[string]interface{} `yaml:"emscoring.18"`
	Emscoring_19     map[string]interface{} `yaml:"emscoring.19"`
	Emscoring_20     map[string]interface{} `yaml:"emscoring.20"`
	Emscoring_21     map[string]interface{} `yaml:"emscoring.21"`
	Emscoring_22     map[string]interface{} `yaml:"emscoring.22"`
	Emscoring_23     map[string]interface{} `yaml:"emscoring.23"`
	Emscoring_24     map[string]interface{} `yaml:"emscoring.24"`
	Emscoring_25     map[string]interface{} `yaml:"emscoring.25"`
	Mdscoring        map[string]interface{} `yaml:"mdscoring"`
	Mdscoring_0      map[string]interface{} `yaml:"mdscoring.0"`
	Mdscoring_1      map[string]interface{} `yaml:"mdscoring.1"`
	Mdscoring_2      map[string]interface{} `yaml:"mdscoring.2"`
	Mdscoring_3      map[string]interface{} `yaml:"mdscoring.3"`
	Mdscoring_4      map[string]interface{} `yaml:"mdscoring.4"`
	Mdscoring_5      map[string]interface{} `yaml:"mdscoring.5"`
	Mdscoring_6      map[string]interface{} `yaml:"mdscoring.6"`
	Mdscoring_7      map[string]interface{} `yaml:"mdscoring.7"`
	Mdscoring_8      map[string]interface{} `yaml:"mdscoring.8"`
	Mdscoring_9      map[string]interface{} `yaml:"mdscoring.9"`
	Mdscoring_10     map[string]interface{} `yaml:"mdscoring.10"`
	Mdscoring_11     map[string]interface{} `yaml:"mdscoring.11"`
	Mdscoring_12     map[string]interface{} `yaml:"mdscoring.12"`
	Mdscoring_13     map[string]interface{} `yaml:"mdscoring.13"`
	Mdscoring_14     map[string]interface{} `yaml:"mdscoring.14"`
	Mdscoring_15     map[string]interface{} `yaml:"mdscoring.15"`
	Mdscoring_16     map[string]interface{} `yaml:"mdscoring.16"`
	Mdscoring_17     map[string]interface{} `yaml:"mdscoring.17"`
	Mdscoring_18     map[string]interface{} `yaml:"mdscoring.18"`
	Mdscoring_19     map[string]interface{} `yaml:"mdscoring.19"`
	Mdscoring_20     map[string]interface{} `yaml:"mdscoring.20"`
	Mdscoring_21     map[string]interface{} `yaml:"mdscoring.21"`
	Mdscoring_22     map[string]interface{} `yaml:"mdscoring.22"`
	Mdscoring_23     map[string]interface{} `yaml:"mdscoring.23"`
	Mdscoring_24     map[string]interface{} `yaml:"mdscoring.24"`
	Mdscoring_25     map[string]interface{} `yaml:"mdscoring.25"`
	Caprieval        map[string]interface{} `yaml:"caprieval"`
	Caprieval_0      map[string]interface{} `yaml:"caprieval.0"`
	Caprieval_1      map[string]interface{} `yaml:"caprieval.1"`
	Caprieval_2      map[string]interface{} `yaml:"caprieval.2"`
	Caprieval_3      map[string]interface{} `yaml:"caprieval.3"`
	Caprieval_4      map[string]interface{} `yaml:"caprieval.4"`
	Caprieval_5      map[string]interface{} `yaml:"caprieval.5"`
	Caprieval_6      map[string]interface{} `yaml:"caprieval.6"`
	Caprieval_7      map[string]interface{} `yaml:"caprieval.7"`
	Caprieval_8      map[string]interface{} `yaml:"caprieval.8"`
	Caprieval_9      map[string]interface{} `yaml:"caprieval.9"`
	Caprieval_10     map[string]interface{} `yaml:"caprieval.10"`
	Caprieval_11     map[string]interface{} `yaml:"caprieval.11"`
	Caprieval_12     map[string]interface{} `yaml:"caprieval.12"`
	Caprieval_13     map[string]interface{} `yaml:"caprieval.13"`
	Caprieval_14     map[string]interface{} `yaml:"caprieval.14"`
	Caprieval_15     map[string]interface{} `yaml:"caprieval.15"`
	Caprieval_16     map[string]interface{} `yaml:"caprieval.16"`
	Caprieval_17     map[string]interface{} `yaml:"caprieval.17"`
	Caprieval_18     map[string]interface{} `yaml:"caprieval.18"`
	Caprieval_19     map[string]interface{} `yaml:"caprieval.19"`
	Caprieval_20     map[string]interface{} `yaml:"caprieval.20"`
	Caprieval_21     map[string]interface{} `yaml:"caprieval.21"`
	Caprieval_22     map[string]interface{} `yaml:"caprieval.22"`
	Caprieval_23     map[string]interface{} `yaml:"caprieval.23"`
	Caprieval_24     map[string]interface{} `yaml:"caprieval.24"`
	Caprieval_25     map[string]interface{} `yaml:"caprieval.25"`
	Clustfcc         map[string]interface{} `yaml:"clustfcc"`
	Clustfcc_0       map[string]interface{} `yaml:"clustfcc.0"`
	Clustfcc_1       map[string]interface{} `yaml:"clustfcc.1"`
	Clustfcc_2       map[string]interface{} `yaml:"clustfcc.2"`
	Clustfcc_3       map[string]interface{} `yaml:"clustfcc.3"`
	Clustfcc_4       map[string]interface{} `yaml:"clustfcc.4"`
	Clustfcc_5       map[string]interface{} `yaml:"clustfcc.5"`
	Clustfcc_6       map[string]interface{} `yaml:"clustfcc.6"`
	Clustfcc_7       map[string]interface{} `yaml:"clustfcc.7"`
	Clustfcc_8       map[string]interface{} `yaml:"clustfcc.8"`
	Clustfcc_9       map[string]interface{} `yaml:"clustfcc.9"`
	Clustfcc_10      map[string]interface{} `yaml:"clustfcc.10"`
	Clustfcc_11      map[string]interface{} `yaml:"clustfcc.11"`
	Clustfcc_12      map[string]interface{} `yaml:"clustfcc.12"`
	Clustfcc_13      map[string]interface{} `yaml:"clustfcc.13"`
	Clustfcc_14      map[string]interface{} `yaml:"clustfcc.14"`
	Clustfcc_15      map[string]interface{} `yaml:"clustfcc.15"`
	Clustfcc_16      map[string]interface{} `yaml:"clustfcc.16"`
	Clustfcc_17      map[string]interface{} `yaml:"clustfcc.17"`
	Clustfcc_18      map[string]interface{} `yaml:"clustfcc.18"`
	Clustfcc_19      map[string]interface{} `yaml:"clustfcc.19"`
	Clustfcc_20      map[string]interface{} `yaml:"clustfcc.20"`
	Clustfcc_21      map[string]interface{} `yaml:"clustfcc.21"`
	Clustfcc_22      map[string]interface{} `yaml:"clustfcc.22"`
	Clustfcc_23      map[string]interface{} `yaml:"clustfcc.23"`
	Clustfcc_24      map[string]interface{} `yaml:"clustfcc.24"`
	Clustfcc_25      map[string]interface{} `yaml:"clustfcc.25"`
	Clustrmsd        map[string]interface{} `yaml:"clustrmsd"`
	Clustrmsd_0      map[string]interface{} `yaml:"clustrmsd.0"`
	Clustrmsd_1      map[string]interface{} `yaml:"clustrmsd.1"`
	Clustrmsd_2      map[string]interface{} `yaml:"clustrmsd.2"`
	Clustrmsd_3      map[string]interface{} `yaml:"clustrmsd.3"`
	Clustrmsd_4      map[string]interface{} `yaml:"clustrmsd.4"`
	Clustrmsd_5      map[string]interface{} `yaml:"clustrmsd.5"`
	Clustrmsd_6      map[string]interface{} `yaml:"clustrmsd.6"`
	Clustrmsd_7      map[string]interface{} `yaml:"clustrmsd.7"`
	Clustrmsd_8      map[string]interface{} `yaml:"clustrmsd.8"`
	Clustrmsd_9      map[string]interface{} `yaml:"clustrmsd.9"`
	Clustrmsd_10     map[string]interface{} `yaml:"clustrmsd.10"`
	Clustrmsd_11     map[string]interface{} `yaml:"clustrmsd.11"`
	Clustrmsd_12     map[string]interface{} `yaml:"clustrmsd.12"`
	Clustrmsd_13     map[string]interface{} `yaml:"clustrmsd.13"`
	Clustrmsd_14     map[string]interface{} `yaml:"clustrmsd.14"`
	Clustrmsd_15     map[string]interface{} `yaml:"clustrmsd.15"`
	Clustrmsd_16     map[string]interface{} `yaml:"clustrmsd.16"`
	Clustrmsd_17     map[string]interface{} `yaml:"clustrmsd.17"`
	Clustrmsd_18     map[string]interface{} `yaml:"clustrmsd.18"`
	Clustrmsd_19     map[string]interface{} `yaml:"clustrmsd.19"`
	Clustrmsd_20     map[string]interface{} `yaml:"clustrmsd.20"`
	Clustrmsd_21     map[string]interface{} `yaml:"clustrmsd.21"`
	Clustrmsd_22     map[string]interface{} `yaml:"clustrmsd.22"`
	Clustrmsd_23     map[string]interface{} `yaml:"clustrmsd.23"`
	Clustrmsd_24     map[string]interface{} `yaml:"clustrmsd.24"`
	Clustrmsd_25     map[string]interface{} `yaml:"clustrmsd.25"`
	Rmsdmatrix       map[string]interface{} `yaml:"rmsdmatrix"`
	Rmsdmatrix_0     map[string]interface{} `yaml:"rmsdmatrix.0"`
	Rmsdmatrix_1     map[string]interface{} `yaml:"rmsdmatrix.1"`
	Rmsdmatrix_2     map[string]interface{} `yaml:"rmsdmatrix.2"`
	Rmsdmatrix_3     map[string]interface{} `yaml:"rmsdmatrix.3"`
	Rmsdmatrix_4     map[string]interface{} `yaml:"rmsdmatrix.4"`
	Rmsdmatrix_5     map[string]interface{} `yaml:"rmsdmatrix.5"`
	Rmsdmatrix_6     map[string]interface{} `yaml:"rmsdmatrix.6"`
	Rmsdmatrix_7     map[string]interface{} `yaml:"rmsdmatrix.7"`
	Rmsdmatrix_8     map[string]interface{} `yaml:"rmsdmatrix.8"`
	Rmsdmatrix_9     map[string]interface{} `yaml:"rmsdmatrix.9"`
	Rmsdmatrix_10    map[string]interface{} `yaml:"rmsdmatrix.10"`
	Rmsdmatrix_11    map[string]interface{} `yaml:"rmsdmatrix.11"`
	Rmsdmatrix_12    map[string]interface{} `yaml:"rmsdmatrix.12"`
	Rmsdmatrix_13    map[string]interface{} `yaml:"rmsdmatrix.13"`
	Rmsdmatrix_14    map[string]interface{} `yaml:"rmsdmatrix.14"`
	Rmsdmatrix_15    map[string]interface{} `yaml:"rmsdmatrix.15"`
	Rmsdmatrix_16    map[string]interface{} `yaml:"rmsdmatrix.16"`
	Rmsdmatrix_17    map[string]interface{} `yaml:"rmsdmatrix.17"`
	Rmsdmatrix_18    map[string]interface{} `yaml:"rmsdmatrix.18"`
	Rmsdmatrix_19    map[string]interface{} `yaml:"rmsdmatrix.19"`
	Rmsdmatrix_20    map[string]interface{} `yaml:"rmsdmatrix.20"`
	Rmsdmatrix_21    map[string]interface{} `yaml:"rmsdmatrix.21"`
	Rmsdmatrix_22    map[string]interface{} `yaml:"rmsdmatrix.22"`
	Rmsdmatrix_23    map[string]interface{} `yaml:"rmsdmatrix.23"`
	Rmsdmatrix_24    map[string]interface{} `yaml:"rmsdmatrix.24"`
	Rmsdmatrix_25    map[string]interface{} `yaml:"rmsdmatrix.25"`
	Seletop          map[string]interface{} `yaml:"seletop"`
	Seletop_0        map[string]interface{} `yaml:"seletop.0"`
	Seletop_1        map[string]interface{} `yaml:"seletop.1"`
	Seletop_2        map[string]interface{} `yaml:"seletop.2"`
	Seletop_3        map[string]interface{} `yaml:"seletop.3"`
	Seletop_4        map[string]interface{} `yaml:"seletop.4"`
	Seletop_5        map[string]interface{} `yaml:"seletop.5"`
	Seletop_6        map[string]interface{} `yaml:"seletop.6"`
	Seletop_7        map[string]interface{} `yaml:"seletop.7"`
	Seletop_8        map[string]interface{} `yaml:"seletop.8"`
	Seletop_9        map[string]interface{} `yaml:"seletop.9"`
	Seletop_10       map[string]interface{} `yaml:"seletop.10"`
	Seletop_11       map[string]interface{} `yaml:"seletop.11"`
	Seletop_12       map[string]interface{} `yaml:"seletop.12"`
	Seletop_13       map[string]interface{} `yaml:"seletop.13"`
	Seletop_14       map[string]interface{} `yaml:"seletop.14"`
	Seletop_15       map[string]interface{} `yaml:"seletop.15"`
	Seletop_16       map[string]interface{} `yaml:"seletop.16"`
	Seletop_17       map[string]interface{} `yaml:"seletop.17"`
	Seletop_18       map[string]interface{} `yaml:"seletop.18"`
	Seletop_19       map[string]interface{} `yaml:"seletop.19"`
	Seletop_20       map[string]interface{} `yaml:"seletop.20"`
	Seletop_21       map[string]interface{} `yaml:"seletop.21"`
	Seletop_22       map[string]interface{} `yaml:"seletop.22"`
	Seletop_23       map[string]interface{} `yaml:"seletop.23"`
	Seletop_24       map[string]interface{} `yaml:"seletop.24"`
	Seletop_25       map[string]interface{} `yaml:"seletop.25"`
	Seletopclusts    map[string]interface{} `yaml:"seletopclusts"`
	Seletopclusts_0  map[string]interface{} `yaml:"seletopclusts.0"`
	Seletopclusts_1  map[string]interface{} `yaml:"seletopclusts.1"`
	Seletopclusts_2  map[string]interface{} `yaml:"seletopclusts.2"`
	Seletopclusts_3  map[string]interface{} `yaml:"seletopclusts.3"`
	Seletopclusts_4  map[string]interface{} `yaml:"seletopclusts.4"`
	Seletopclusts_5  map[string]interface{} `yaml:"seletopclusts.5"`
	Seletopclusts_6  map[string]interface{} `yaml:"seletopclusts.6"`
	Seletopclusts_7  map[string]interface{} `yaml:"seletopclusts.7"`
	Seletopclusts_8  map[string]interface{} `yaml:"seletopclusts.8"`
	Seletopclusts_9  map[string]interface{} `yaml:"seletopclusts.9"`
	Seletopclusts_10 map[string]interface{} `yaml:"seletopclusts.10"`
	Seletopclusts_11 map[string]interface{} `yaml:"seletopclusts.11"`
	Seletopclusts_12 map[string]interface{} `yaml:"seletopclusts.12"`
	Seletopclusts_13 map[string]interface{} `yaml:"seletopclusts.13"`
	Seletopclusts_14 map[string]interface{} `yaml:"seletopclusts.14"`
	Seletopclusts_15 map[string]interface{} `yaml:"seletopclusts.15"`
	Seletopclusts_16 map[string]interface{} `yaml:"seletopclusts.16"`
	Seletopclusts_17 map[string]interface{} `yaml:"seletopclusts.17"`
	Seletopclusts_18 map[string]interface{} `yaml:"seletopclusts.18"`
	Seletopclusts_19 map[string]interface{} `yaml:"seletopclusts.19"`
	Seletopclusts_20 map[string]interface{} `yaml:"seletopclusts.20"`
	Seletopclusts_21 map[string]interface{} `yaml:"seletopclusts.21"`
	Seletopclusts_22 map[string]interface{} `yaml:"seletopclusts.22"`
	Seletopclusts_23 map[string]interface{} `yaml:"seletopclusts.23"`
	Seletopclusts_24 map[string]interface{} `yaml:"seletopclusts.24"`
	Seletopclusts_25 map[string]interface{} `yaml:"seletopclusts.25"`
}
