[general]
dataset_path = "/Users/rvhonorato/repos/benchmark-tools/example"
haddock_exec = "PYTHONPATH=/Users/rvhonorato/repos/haddock /Users/rvhonorato/software/miniconda2/bin/python /Users/rvhonorato/repos/haddock/Haddock/RunHaddock.py"
# haddock_exec = "PYTHONPATH=/Users/rvhonorato/repos/haddock3/src /Users/rvhonorato/haddock3_python_env/bin/python /Users/rvhonorato/repos/haddock3/src/haddock/clis/cli.py"

receptor_suffix = '_r_u'
ligand_suffix = '_l_u'
# concurrent_jobs = 10

# ==============================

[scenario_1]
run_name = 'true-interface'
# rigidbody.sampling = 1000
# rigidbody.ambig_fname = "ambig.tbl"
# rigidbody.randremoval = false
ambig_tbl = 'ambig.tbl'


# [scenario_2]
# run_name = 'center-of-mass'
# cmrest = true

# [scenario_3]
# run_name = 'surface-restraints'
# surfrest = true

# ==============================
