# Basic configuration
ClusterName=localhost
ControlMachine=localhost
SlurmctldHost=localhost
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm
SlurmdSpoolDir=/var/spool/slurm
SlurmUser=slurm
SlurmdUser=root
SlurmdParameters=no_getaddrinfo

# Node configuration
NodeName=localhost Procs=4 RealMemory=4000 State=UNKNOWN
PartitionName=debug Nodes=localhost Default=YES MaxTime=INFINITE State=UP
