name: linting

on: push

permissions: read-all

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod download

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
