name: linting

on: push

permissions: read-all

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod download

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
