name: unittests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
