name: unittests

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.out

      - name: Run codacy-coverage-reporter
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
